services:
  - type: web
    name: faarook-api
    runtime: node
    plan: free
    region: virginia
    buildCommand: npm ci --include=dev && npm run build
    startCommand: node dist/server.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
