name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: backend
        run: npm ci

      - name: TypeScript build
        working-directory: backend
        run: npm run build

      - name: Validate OpenAPI spec
        working-directory: backend
        run: npm run spec:check

      - name: Generate Postman collection
        working-directory: backend
        run: npm run spec:postman

      - name: Upload Postman artifacts
        uses: actions/upload-artifact@v4
        with:
          name: postman-artifacts
          path: |
            backend/postman_collection.json
            backend/postman_environment.json

      - name: Optionally publish to Postman (if secrets set)
        if: ${{ secrets.POSTMAN_API_KEY && secrets.POSTMAN_WORKSPACE_ID }}
        working-directory: backend
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
          POSTMAN_WORKSPACE_ID: ${{ secrets.POSTMAN_WORKSPACE_ID }}
        run: |
          node -e "const fs=require('fs');const c=JSON.parse(fs.readFileSync('postman_collection.json','utf8'));fs.writeFileSync('postman_wrapped.json', JSON.stringify({collection:c}))"
          curl -sS -X POST "https://api.getpostman.com/collections?workspace=${POSTMAN_WORKSPACE_ID}" \
            -H "X-Api-Key: ${POSTMAN_API_KEY}" \
            -H "Content-Type: application/json" \
            --data-binary @postman_wrapped.json
